# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vsfleet < Formula
  desc "Read-only vSphere estate assessment and diagnostics across every vCenter"
  homepage "https://github.com/Easonliuuuuu/vsfleet"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v0.6.2/vsfleet_0.6.2_darwin_amd64.tar.gz"
      sha256 "b4321804ba973c7999914fe8be8e91bc035acb63bdba551d54f818ada6139bdc"

      define_method(:install) do
        bin.install "vsfleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v0.6.2/vsfleet_0.6.2_darwin_arm64.tar.gz"
      sha256 "f2c2c7db48905a949a835c42dc5fe6527b04f0df74433aeb0da1b9a07a3ec171"

      define_method(:install) do
        bin.install "vsfleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v0.6.2/vsfleet_0.6.2_linux_amd64.tar.gz"
      sha256 "fdb02568046bbe95ef737f2724ef83970987d86c6aad2a2fa9d76184791db152"
      define_method(:install) do
        bin.install "vsfleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v0.6.2/vsfleet_0.6.2_linux_arm64.tar.gz"
      sha256 "a831d4216ee26f3f36f553dcea0945e163f695677f57dc72c852762bc3020daa"
      define_method(:install) do
        bin.install "vsfleet"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vsfleet --version")
  end
end
