# This file was generated by GoReleaser. DO NOT EDIT.
cask "vsfleet" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "4c851dfe0e3e0c4199a75f4c36b914d3dc6a71bec711998a0df812e03b010e30"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e0d149e393f31421deb209fbfd1ff9da8b95dc4d5549738b14f345c63b717912"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8a7b70d03f35c465771063d21127c12347faa6c4e3710f5a3dc0a8c70088f438"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1f19141d72f184358112491efa4b6d6c6dc1c07ed5dd40656551ce4becf9e5d"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vsfleet"
  desc "Operate multiple VMware vCenter servers from one terminal"
  homepage "https://github.com/easonliuuuuu/vsfleet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vsfleet"

  # No zap stanza required
end
