# This file was generated by GoReleaser. DO NOT EDIT.
cask "vsfleet" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "5efdf24e7f081fc3bd31cdcd216a8b8b498e9df44cffc0da24f35df92595cf8f"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca958deff7e9eba198c7515cd72c144a5645e00009e876bb2f26caa5926d972d"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6248ea5baeb51a52ecf857bb0bf9ed1f677d2f4a128e3956c4335f6bde61e88e"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d33ff8b63f83cef1c77b9d01f7ec1d8321663f33558ce8eb1dec4e04cf4a767"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vsfleet"
  desc "Read-only vSphere estate assessment and diagnostics across every vCenter"
  homepage "https://github.com/easonliuuuuu/vsfleet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vsfleet"

  # No zap stanza required
end
