# This file was generated by GoReleaser. DO NOT EDIT.
cask "vsfleet" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "4bcb1e6ff794e90b44d586b2de0250ce35a4b87bc59a30f6370a2ef18d554948"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff7dea4cb08a4f78b94174be367857d21964bc711a7c7e2dc9c81fe691d7463f"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a462f6fb7965040682c38548e016fdd72de2029a88309db102617d14ab608e78"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4431c7c3e981ccd3814a146a75955b41540bc55a61e19500b966140edfb2ba2f"
      url "https://github.com/Easonliuuuuu/vsfleet/releases/download/v#{version}/vsfleet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vsfleet"
  desc "Operate multiple VMware vCenter servers from one terminal"
  homepage "https://github.com/easonliuuuuu/vsfleet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vsfleet"

  # No zap stanza required
end
